.TH CONFIGURE_NDISWRAPPER "8" "July 2007" "" ""
.SH NAME
configure-ndiswrapper \- GUI for windows (ndis) driver installation
.SH SYNOPSIS
\fBconfigure-ndiswrapper\fR
.SH DESCRIPTION
The purpose of \fIconfigure-ndiswrapper\fR is to provide a simple graphical
user interface to the installation of windows drivers.
.PP
\fIconfigure-ndiswrapper\fR takes no options.
.PP
.SH AUTHOR
This manual page was written by Kel Modderman <kel@otaku42.de> for
the Debian GNU system (but may be used by others).
